// Optional real-browser QA. Uses an isolated browser context and local mock API only.
import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.SHOPPING_PLAYWRIGHT_PATH || 'playwright');
const base = process.env.SHOPPING_PREVIEW_URL || 'http://127.0.0.1:4310';
if (!['127.0.0.1', 'localhost'].includes(new URL(base).hostname)) throw new Error('Browser QA only accepts a local mock preview');
const output = resolve(import.meta.dirname, '../../.codex-tmp/shopping-browser-qa');
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.SHOPPING_BROWSER_EXE ? { executablePath: process.env.SHOPPING_BROWSER_EXE } : {}) });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const results = [];
function assert(value, message) { if (!value) throw new Error(message); results.push(message); }
try {
  await page.goto(base);
  await page.waitForFunction(() => !document.getElementById('search-button').disabled);
  assert(await page.title() === '一杯之间 · 本地购物助手', 'Chinese page title and initial UI loaded');
  await page.screenshot({ path: resolve(output, 'desktop-initial.png'), fullPage: true });
  await page.getByRole('button', { name: '寻找咖啡' }).click();
  await page.getByRole('button', { name: '查看最终报价' }).first().waitFor();
  assert(await page.getByRole('button', { name: '查看最终报价' }).count() === 2, 'Two valid latte candidates displayed');
  await page.getByRole('button', { name: '查看最终报价' }).nth(1).click();
  await page.getByText('含全部费用的最终报价超过预算，不能购买。').waitFor();
  assert(await page.getByRole('button', { name: '确认并模拟购买' }).isDisabled(), '31 yuan final total blocked under 30 yuan budget');
  await page.getByRole('button', { name: '查看最终报价' }).first().click();
  await page.getByRole('button', { name: '确认并模拟购买' }).waitFor();
  await page.waitForFunction(() => !document.getElementById('confirm-button').disabled);
  assert((await page.locator('#quote-content').textContent()).includes('¥28.00'), 'All-in 28 yuan quote displayed');
  await page.screenshot({ path: resolve(output, 'desktop-quote.png'), fullPage: true });
  await page.getByRole('button', { name: '确认并模拟购买' }).click();
  await page.getByText('模拟订单已确认', { exact: true }).waitFor();
  assert(await page.getByText('模拟已支付', { exact: true }).isVisible(), 'Explicit UI click leads to mock paid order');
  assert(await page.getByText('制作中', { exact: true }).isVisible(), 'Fulfillment remains preparing, separate from payment');
  const attempt = await page.locator('#order-content').textContent();
  await page.reload();
  await page.getByText('模拟订单已确认', { exact: true }).waitFor();
  assert(await page.locator('#order-content').textContent() === attempt, 'Reload recovers original order and attempt');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: resolve(output, 'mobile-order.png'), fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile page has no horizontal overflow');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: '寻找咖啡' }).click();
  await page.getByRole('button', { name: '查看最终报价' }).first().waitFor();
  await page.getByRole('button', { name: '查看最终报价' }).first().click();
  await page.waitForFunction(() => !document.getElementById('confirm-button').disabled);
  const id = await page.evaluate(() => localStorage.getItem('ocp-shopping-session-id'));
  await page.route(`**/api/sessions/${id}/confirm`, async route => { await route.fetch(); await route.abort('failed'); });
  await page.route(`**/api/sessions/${id}`, route => route.abort('failed'));
  await page.getByRole('button', { name: '确认并模拟购买' }).click();
  await page.getByText('确认请求的结果未知，请查询原购买结果；不要重新购买。').waitFor();
  assert(await page.getByRole('button', { name: '寻找咖啡' }).isDisabled(), 'Lost browser response locks new purchase flow');
  assert(await page.getByRole('button', { name: '查询原购买结果' }).isVisible(), 'Unknown result keeps recovery action available');
  assert(await page.getByRole('button', { name: '取消本次购买' }).isDisabled(), 'Unknown result disables cancellation and replacement');
  assert(await page.getByText('购买结果待查询', { exact: true }).isVisible(), 'Unknown result never retains a stale success heading');
  await page.unrouteAll();
  await page.getByRole('button', { name: '查询原购买结果' }).click();
  await page.getByText('模拟订单已确认', { exact: true }).waitFor();
  assert(await page.getByRole('button', { name: '确认并模拟购买' }).isDisabled(), 'Recovery shows original confirmed purchase without another checkout');
  assert(errors.length === 0, 'No browser JavaScript exceptions');
  const report = { status: 'passed', scope: 'A-only deterministic mock browser QA', checks: results, errors };
  await writeFile(resolve(output, 'report.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report));
} finally { await browser.close(); }
